#!/usr/bin/env bash                                                                                                                                       

# Update Nginx configuration to listen on port 80
sed -i 's/^\s*listen\s*\(.*\)/    listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
