#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

t=0

while [ $t -lt 10 ]
do
  if [ $t -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( t++ ))
done
